// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCBJZeuz8zUWSr_wXsW83O9euuzP0j1vs',
    appId: '1:830764828907:web:5be92203c72a2a4e9b56ae',
    messagingSenderId: '830764828907',
    projectId: 'login-page-using-firebas-86e1e',
    authDomain: 'login-page-using-firebas-86e1e.firebaseapp.com',
    storageBucket: 'login-page-using-firebas-86e1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQzAQUzVbJTl5dyMuGkwm_FXEzwJqVrME',
    appId: '1:830764828907:android:0afe7580390d84579b56ae',
    messagingSenderId: '830764828907',
    projectId: 'login-page-using-firebas-86e1e',
    storageBucket: 'login-page-using-firebas-86e1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIT8dzZhShyCNxpvQJNpq-LsyAo8FD2Vw',
    appId: '1:830764828907:ios:5a81f1018f16cbbf9b56ae',
    messagingSenderId: '830764828907',
    projectId: 'login-page-using-firebas-86e1e',
    storageBucket: 'login-page-using-firebas-86e1e.appspot.com',
    iosBundleId: 'com.example.loginPageUsingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIT8dzZhShyCNxpvQJNpq-LsyAo8FD2Vw',
    appId: '1:830764828907:ios:5a81f1018f16cbbf9b56ae',
    messagingSenderId: '830764828907',
    projectId: 'login-page-using-firebas-86e1e',
    storageBucket: 'login-page-using-firebas-86e1e.appspot.com',
    iosBundleId: 'com.example.loginPageUsingFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCBJZeuz8zUWSr_wXsW83O9euuzP0j1vs',
    appId: '1:830764828907:web:88aecf4cd11114ef9b56ae',
    messagingSenderId: '830764828907',
    projectId: 'login-page-using-firebas-86e1e',
    authDomain: 'login-page-using-firebas-86e1e.firebaseapp.com',
    storageBucket: 'login-page-using-firebas-86e1e.appspot.com',
  );
}
